services:
  app:
    container_name: web-app
    depends_on:
      - api
    build: ./client
    ports:
      - 3000:3000
    env_file:
      - ./client/.env
    networks:
      - web-network

  api:
    container_name: web-api
    build: ./server
    ports:
      - 8000:8000
    env_file:
      - ./server/.env
    networks:
      - web-network
    volumes:
      - web-api-data:/app/data

networks:
  web-network:
    driver: bridge

volumes:
  web-api-data:
    name: web-api-data
